# swagger.yml

openapi: 3.0.0
info:
  title: "Trail Management API"
  description: "An API for Managing Trails and their Features."
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Trail:
      type: object
      properties:
        TrailName:
          type: string
        TrailSummary:
          type: string
        TrailDescription:
          type: string
        Difficulty:
          type: string
        Location:
          type: string
        Length:
          type: number
          format: float
        ElevationGain:
          type: number
          format: float
        RouteType:
          type: string
        OwnerID:
          type: integer
        Pt1_lat:
          type: number
          format: float
        Pt1_long:
          type: number
          format: float
        Pt1_desc:
          type: string
        Pt2_lat:
          type: number
          format: float
        Pt2_long:
          type: number
          format: float
        Pt2_desc:
          type: string
        Pt3_lat:
          type: number
          format: float
        Pt3_long:
          type: number
          format: float
        Pt3_desc:
          type: string
        Pt4_lat:
          type: number
          format: float
        Pt4_long:
          type: number
          format: float
        Pt4_desc:
          type: string
        Pt5_lat:
          type: number
          format: float
        Pt5_long:
          type: number
          format: float
        Pt5_desc:
          type: string

    Feature:
      type: object
      properties:
        TrailFeature:
          type: string

    TrailFeatureLink:
      type: object
      properties:
        TrailID:
          type: integer
        TrailFeatureID:
          type: integer

    User:
      type: object
      properties:
        EmailAddress:
          type: string
        Role:
          type: string

paths:
  /trails:
    get:
      operationId: "endpoints.read_all_trails"
      summary: "Get all trails"
      tags:
        - Trail
      responses:
        "200":
          description: "List of all trails"
    post:
      operationId: "endpoints.create_trail"
      summary: "Create a trail"
      tags:
        - Trail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Trail"
      responses:
        "201":
          description: "Trail created successfully"

  /trails/{trail_id}:
    get:
      operationId: "endpoints.read_one_trail"
      summary: "Get a trail by ID"
      tags:
        - Trail
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Trail details"
    put:
      operationId: "endpoints.update_trail"
      summary: "Update a trail"
      tags:
        - Trail
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Trail"
      responses:
        "201":
          description: "Trail updated successfully"
    delete:
      operationId: "endpoints.delete_trail"
      summary: "Delete a trail"
      tags:
        - Trail
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Trail deleted successfully"

  /features:
    get:
      operationId: "endpoints.read_all_features"
      summary: "Get all features"
      tags:
        - Feature
      responses:
        "200":
          description: "List of all features"
    post:
      operationId: "endpoints.create_feature"
      summary: "Create a feature"
      tags:
        - Feature
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Feature"
      responses:
        "201":
          description: "Feature created successfully"

  /features/{feature_id}:
    get:
      operationId: "endpoints.read_one_feature"
      summary: "Get a feature by ID"
      tags:
        - Feature
      parameters:
        - name: feature_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Feature details"
    put:
      operationId: "endpoints.update_feature"
      summary: "Update a feature"
      tags:
        - Feature
      parameters:
        - name: feature_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Feature"
      responses:
        "201":
          description: "Feature updated successfully"
    delete:
      operationId: "endpoints.delete_feature"
      summary: "Delete a feature"
      tags:
        - Feature
      parameters:
        - name: feature_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Feature deleted successfully"

  /trail-features:
      post:
        operationId: "endpoints.create_trail_feature"
        summary: "Link a feature to a trail"
        tags:
          - TrailFeature
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TrailFeatureLink"
        responses:
          "201":
            description: "Trail-feature relationship created successfully"
      get:
        operationId: "endpoints.read_all_trail_features"
        summary: "Get all trail-feature links"
        tags:
          - TrailFeature
        responses:
          "200":
            description: "List of all trail-feature links"

  /users:
    get:
      operationId: "endpoints.read_all_users"
      summary: "Get all users"
      tags:
        - User
      responses:
        "200":
          description: "List of all users"
    post:
      operationId: "endpoints.create_user"
      summary: "Create a user"
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: "User created successfully"

  /users/{user_id}:
    get:
      operationId: "endpoints.read_one_user"
      summary: "Get a user by ID"
      tags:
        - User
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "User details"
    delete:
      operationId: "endpoints.delete_user"
      summary: "Delete a user"
      tags:
        - User
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "User deleted successfully"
    put:
      operationId: "endpoints.update_user"
      summary: "Update a user"
      tags:
        - User
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: "User updated successfully"